MakeMake - PanelSidetray
funkhaus/factory pull request #37
Opened 2020-07-14 22:43 UTC by dChiamp

Components included in this PR are:

1. PanelSidetray

## Notes
Has separate story for active item. 
Added a click event handler that may not be needed
Is this used on mobile?

2020-07-15 14:23 UTC, drewbaker requested changes
Can you add the little film icon into this. Position in off the left outside of the panel (position: absolute; left: -20px (or whatever).

<img width="287" alt="Screen Shot 2020-07-15 at 4 22 19 PM" src="https://user-images.githubusercontent.com/475015/87556792-5c6a3300-c6b7-11ea-8eff-f9945ec058c3.png">

The last thumbnail shouldn't be hard up against the bottom of the thumbtray. Should have same spacing around it as the top.

2020-07-15 14:23 UTC, drewbaker commented on src/components/PanelSidetray/PanelSidetray.vue
> +            }
Don't need to nest these. Give H4 a class!

Also H4 will need some padding so it positions nicely in the thumbnail

2020-07-15 14:23 UTC, drewbaker commented on src/components/PanelSidetray/PanelSidetray.vue
> +            @click.native="handleClick"
Don't need this click event. I'm going to make any click on the entire component close the panel.

2020-07-16 00:22 UTC, dChiamp commented
OK Made these updates.

I don't think the `icon-reel` svg should be part of this component but I included it anyway.
I would think it's its own position fixed component on the page that translates the entire page over to reveal `panel-sidetray` on click:
<img width="708" alt="Screen Shot 2020-07-15 at 5 05 43 PM" src="https://user-images.githubusercontent.com/13562688/87612050-63e10a80-c6be-11ea-902f-8d8e42e594da.png">

I repositioned things to make that easier.
Also I had to remove  `overflow-y: scroll`  to show the svg (see note in component).

I know we shouldnt use the `index` /  `i` as a key, so you'll notice there's a duplicate key error in the console bc of how i mocked up manyPages in the story.  It wont be an issue with real data and i didnt want to use `index` so i left it intentionally.

2020-07-16 15:23 UTC, drewbaker requested changes
See my notes for how to do this correctly

2020-07-16 15:23 UTC, drewbaker commented on src/components/PanelSidetray/PanelSidetray.vue
> +    </div>
How you do this, and have it work correctly is this:

```
<div class="panel-sidetray"> // height --unit-100vh, position: fixed, right: 0; transform: translateX(100%);
      <svg-film> // Position: absolute, -100px;
       
      <div class="items"> // Height 100%, overflow-y: auto;
              <nuxt-link/>
              <nuxt-link/>
              <nuxt-link/>
      </div>
</div>
```

Getting both the thumbtray and the film SVG to animate smoothly in sync is difficult, but having them together like this makes it really easy.

Have a style in it for the open state, like this:

```
.panel-sidetray {

      .sidetray-opened & {
             transform: translate(0);
      }
}
```

I will then toggle that style on body (so I can also dim the page etc).

2020-08-03 15:28 UTC, merged